from pathlib import Path
p=Path('/mnt/data/v23work/src/main.jsx')
s=p.read_text()
# Student results nav
s=s.replace("'Student':['dashboard','marks','assignments','calendar','classroom','resources','notifications','profile']", "'Student':['dashboard','marks','results','assignments','calendar','classroom','resources','notifications','profile']")
# Link applicationId into student registration pending user
old="const u={...f,username:role==='Student'?f.email.split('@')[0]:f.username,recoveryAnswer:f.recoveryAnswer.trim().toLowerCase(),id:uid('USR'),schoolId:SCHOOL_ID,role,status:'PENDING'};"
new="const approvedStudentApp=role==='Student'?(data.applications||[]).find(a=>a.status==='APPROVED'&&a.className===f.className&&String(a.childName||'').trim().toLowerCase()===f.name.trim().toLowerCase()&&String(a.childSurname||'').trim().toLowerCase()===f.surname.trim().toLowerCase()):null;const u={...f,username:role==='Student'?f.email.split('@')[0]:f.username,recoveryAnswer:f.recoveryAnswer.trim().toLowerCase(),applicationId:approvedStudentApp?.id||'',id:uid('USR'),schoolId:SCHOOL_ID,role,status:'PENDING'};"
s=s.replace(old,new)
# Replace Feedback function
start=s.find('function Feedback({user,data,setData}){')
end=s.find('\nfunction AnnualResults', start)
feedback="""function Feedback({user,data,setData}){const leadership=['Principal','Deputy Principal'].includes(user.role);const [text,setText]=useState('');function submit(){const body=text.trim();if(!body)return;const leaders=(Array.isArray(data?.pendingUsers)?data.pendingUsers:[]).filter(u=>u?.status==='APPROVED'&&(u.role==='Principal'||u.role==='Deputy Principal')&&u.schoolId===SCHOOL_ID).map(u=>u.email).filter(Boolean);const feedbackItem={id:uid('F'),schoolId:user.schoolId,parentEmail:user.email,parentName:user.name||'',text:body,date:new Date().toISOString()};const notes=[...(Array.isArray(data?.notifications)?data.notifications:[]),...leaders.map(email=>({id:uid('N'),title:'New parent feedback',body:`${user.name||'A parent'} submitted new feedback.`,audience:email,schoolId:SCHOOL_ID,feedbackId:feedbackItem.id}))];setData(prev=>({...prev,feedback:[...(prev.feedback||[]),feedbackItem],notifications:notes}));setText('')}return <><HeaderBlock eyebrow=\"PARENT VOICE\" title=\"Feedback\" text={leadership?'Review feedback submitted by parents.':'Send private feedback to the school leadership team.'}/><Panel title={leadership?'Parent feedback':'Submit feedback'}>{leadership?<Table headers={['Parent','Comment','Date']} rows={data.feedback.filter(f=>f.schoolId===user.schoolId).map(f=>[f.parentName||f.parentEmail,f.text,new Date(f.date).toLocaleDateString()])}/>:<><textarea className=\"feedbackBox\" value={text} onChange={e=>setText(e.target.value)} placeholder=\"Write feedback...\"/><button className=\"primary\" onClick={submit}>Submit privately</button></>}</Panel></>}"""
s=s[:start]+feedback+s[end:]
# Replace AnnualResults
start=s.find('function AnnualResults({user,data}){')
end=s.find('\nfunction SettingsPage', start)
results="""function resultSymbol(mark){const n=Number(mark);if(!Number.isFinite(n))return '—';if(n>=80)return 'A';if(n>=70)return 'B';if(n>=60)return 'C';if(n>=50)return 'D';if(n>=40)return 'E';return 'F'}
function examResultFor(st,subject,termKey){const a=getMark(st,subject,`${termKey}_exam`);return a?.mark??null}
function AnnualResults({user,data}){const isStudent=user.role==='Student';const students=isStudent?data.students.filter(s=>s.userId===user.id||s.email===user.email):parentAcceptedStudents(user,data);const [termKey,setTermKey]=useState('t1');const rows=[];students.forEach(st=>{const subjects=[...new Set(st.subjects||[])];subjects.forEach(subject=>{const mark=examResultFor(st,subject,termKey);rows.push({st,subject,mark})})});const valid=rows.filter(r=>Number.isFinite(Number(r.mark)));const aggregate=valid.reduce((sum,r)=>sum+Number(r.mark),0);const average=valid.length?Math.round(aggregate/valid.length):null;const label=TERMS.find(t=>t.key===termKey)?.label||'Term 1';return <><HeaderBlock eyebrow=\"EXAM RESULTS\" title={isStudent?'My Results':'Children’s Results'} text=\"Final results show exam marks only. Test 1 and Test 2 remain in the teacher gradebook but are not displayed here.\"/><Panel title=\"Exam period\"><div className=\"marksToolbarPro gradebookToolbar\"><label>Term<select value={termKey} onChange={e=>setTermKey(e.target.value)}>{TERMS.map(t=><option key={t.key} value={t.key}>{t.label}</option>)}</select></label></div></Panel>{students.length?students.map(st=>{const subjectRows=(st.subjects||[]).map(subject=>{const mark=examResultFor(st,subject,termKey);return [subject,mark??'—',resultSymbol(mark)]});const studentMarks=subjectRows.map(r=>Number(r[1])).filter(Number.isFinite);const total=studentMarks.reduce((a,b)=>a+b,0);const avg=studentMarks.length?Math.round(total/studentMarks.length):null;return <Panel key={st.id} title={`${st.name} ${st.surname} — ${st.className}`}><div className=\"resultsSummaryPro\"><span><b>{label}</b></span><span>Subjects: <b>{studentMarks.length}/{subjectRows.length}</b></span><span>Aggregate: <b>{studentMarks.length?total:'—'}</b></span><span>Average: <b>{avg!==null?avg+'%':'—'}</b></span></div><Table headers={['Subject','Exam mark','Symbol']} rows={subjectRows}/></Panel>}):<Empty text={isStudent?'No learner record is linked to this account.':'No approved learners are linked to this parent.'/>}{!isStudent&&valid.length>0&&<Panel title=\"Selected results summary\"><div className=\"resultsSummaryPro\"><span>Total exam marks: <b>{aggregate}</b></span><span>Average: <b>{average}%</b></span></div></Panel>}</>}"""
s=s[:start]+results+s[end:]
p.write_text(s)
